# Generated by Django 3.2.6 on 2022-11-22 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221123_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_similar',
            field=models.ManyToManyField(default=0, related_name='_accounts_user_user_similar_+', through='accounts.UserSimilar', to=settings.AUTH_USER_MODEL),
        ),
    ]
