# Generated by Django 3.2.6 on 2022-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_similar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersimilar',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
